name: CI (Coq, docker)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker-build:
    strategy:
      fail-fast: false
      matrix:
        coq-version: [ dev , 8.16 ]

    runs-on: ubuntu-latest
    name: ${{ matrix.coq-version }}

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.coq-version }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.coq-version }}
        ocaml_version: default
